import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,setPersistence,browserLocalPersistence,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{getFirestore,collection,doc,setDoc,updateDoc,onSnapshot,serverTimestamp,writeBatch,getDocs,query,orderBy}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js";

const MAX=10*1024*1024,CHUNK=600*1024,QUOTA=700*1024*1024,ROOT="root";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
setPersistence(auth,browserLocalPersistence).catch(console.error);
const e={load:$("loadingScreen"),auth:$("authScreen"),shell:$("appShell"),form:$("authForm"),title:$("authTitle"),lead:$("authLead"),email:$("emailInput"),pass:$("passwordInput"),err:$("authError"),submit:$("authSubmit"),switch:$("switchAuthMode"),eye:$("togglePassword"),user:$("userButton"),menu:$("userMenu"),userEmail:$("userEmail"),avatar:$("avatarInitial"),logout:$("logoutButton"),sidebar:$("sidebar"),shade:$("sidebarShade"),mobile:$("mobileMenuButton"),closeSide:$("closeSidebar"),pageTitle:$("pageTitle"),sub:$("pageSubtitle"),crumbs:$("breadcrumbs"),search:$("searchInput"),folder:$("newFolderButton"),upload:$("uploadButton"),uploadTop:$("uploadTopButton"),emptyUpload:$("emptyUploadButton"),input:$("fileInput"),refresh:$("refreshButton"),sort:$("sortButton"),list:$("fileList"),count:$("itemCount"),empty:$("emptyState"),emptyTitle:$("emptyTitle"),emptyText:$("emptyText"),overlay:$("dropOverlay"),queue:$("uploadQueue"),storageText:$("storageText"),storageBar:$("storageBar"),textDialog:$("textDialog"),textForm:$("textDialogForm"),textTitle:$("textDialogTitle"),textLabel:$("textDialogLabel"),textInput:$("textDialogInput"),textError:$("textDialogError"),textSubmit:$("textDialogSubmit"),confirm:$("confirmDialog"),confirmTitle:$("confirmTitle"),confirmText:$("confirmText"),confirmOk:$("confirmOk"),preview:$("previewDialog"),previewName:$("previewName"),previewMeta:$("previewMeta"),previewBody:$("previewBody"),closePreview:$("closePreview"),toasts:$("toastRegion")};
document.querySelector(".storage-card small").textContent="無料版では1ファイル10MBまで";
let mode="login",user=null,view="files",folder=ROOT,items=[],unsub=null,sort="updated",textResolve=null,drag=0,previewUrl=null;

const show=s=>{e.load.classList.toggle("hidden",s!=="load");e.auth.classList.toggle("hidden",s!=="auth");e.shell.classList.toggle("hidden",s!=="app")};
const toast=(m,t="")=>{const n=document.createElement("div");n.className=`toast ${t}`.trim();n.textContent=m;e.toasts.append(n);setTimeout(()=>n.remove(),4200)};
const msg=x=>({"auth/invalid-email":"メールアドレスの形式が正しくありません。","auth/weak-password":"パスワードは6文字以上にしてください。","auth/email-already-in-use":"このメールアドレスは登録済みです。","auth/invalid-credential":"メールアドレスまたはパスワードが違います。","permission-denied":"Firestoreのルールを確認してください。","resource-exhausted":"Firebaseの無料利用枠に達しました。","unavailable":"Firebaseに接続できませんでした。","cancelled":"キャンセルしました。"}[x?.code]||x?.message||"処理に失敗しました。");
const setMode=m=>{mode=m;const s=m==="signup";e.title.textContent=s?"アカウント作成":"ログイン";e.lead.textContent=s?"新しいソラップBOXを作成します。":"メールアドレスとパスワードを入力してください。";e.submit.textContent=s?"無料で作成":"ログイン";e.switch.textContent=s?"すでにアカウントを持っている":"新しいアカウントを作る";e.err.textContent=""};
e.form.onsubmit=async ev=>{ev.preventDefault();const mail=e.email.value.trim(),pw=e.pass.value;if(!mail||pw.length<6){e.err.textContent="メールアドレスと6文字以上のパスワードを入力してください。";return}e.submit.disabled=true;try{const c=mode==="signup"?await createUserWithEmailAndPassword(auth,mail,pw):await signInWithEmailAndPassword(auth,mail,pw);await setDoc(doc(db,"users",c.user.uid),{uid:c.user.uid,email:c.user.email,updatedAt:serverTimestamp(),...(mode==="signup"?{createdAt:serverTimestamp()}:{})},{merge:true})}catch(x){e.err.textContent=msg(x)}finally{e.submit.disabled=false;setMode(mode)}};
e.switch.onclick=()=>setMode(mode==="login"?"signup":"login");
e.eye.onclick=()=>{e.pass.type=e.pass.type==="text"?"password":"text"};
e.logout.onclick=()=>signOut(auth);
onAuthStateChanged(auth,u=>{user=u;if(unsub)unsub();items=[];folder=ROOT;view="files";if(!u){show("auth");render();return}e.userEmail.textContent=u.email||"sorapbox user";e.avatar.textContent=(u.email||"S")[0].toUpperCase();show("app");unsub=onSnapshot(collection(db,"users",u.uid,"items"),s=>{items=s.docs.map(d=>({id:d.id,...d.data()}));render()},x=>toast(msg(x),"error"))});

const ms=v=>!v?0:typeof v.toMillis==="function"?v.toMillis():v.seconds?v.seconds*1000:new Date(v).getTime()||0;
const date=v=>{const d=new Date(ms(v));return!ms(v)?"たった今":d.toDateString()===new Date().toDateString()?d.toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"}):d.toLocaleDateString("ja-JP",{year:"numeric",month:"short",day:"numeric"})};
const bytes=n=>{if(!n)return"0 B";const u=["B","KB","MB","GB"],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3),v=n/1024**i;return`${v>=10||!i?v.toFixed(0):v.toFixed(1)} ${u[i]}`};
const map=()=>new Map(items.map(x=>[x.id,x]));
function visible(){const q=e.search.value.trim().toLowerCase(),m=map();let a=view==="trash"?items.filter(x=>x.trashed&&!m.get(x.parentId)?.trashed):view==="recent"?items.filter(x=>!x.trashed&&x.type==="file"):items.filter(x=>!x.trashed&&(x.parentId||ROOT)===folder);if(q)a=items.filter(x=>(view==="trash"?x.trashed:!x.trashed)&&String(x.name||"").toLowerCase().includes(q));return a.sort((a,b)=>sort==="name"?String(a.name).localeCompare(String(b.name),"ja",{numeric:true}):a.type!==b.type&&view==="files"?(a.type==="folder"?-1:1):ms(b.updatedAt||b.createdAt)-ms(a.updatedAt||a.createdAt))}
function kind(x){if(x.type==="folder")return["folder","▰","フォルダ"];const m=x.mimeType||"",z=String(x.name||"").split(".").pop().toLowerCase();if(m.startsWith("image/"))return["image","IMG","画像"];if(m.startsWith("video/"))return["video","▶","動画"];if(m.startsWith("audio/"))return["video","♪","音声"];if(m==="application/pdf"||z==="pdf")return["pdf","PDF","PDF"];if(["zip","rar","7z","gz","tar"].includes(z))return["archive","ZIP","圧縮ファイル"];return["",(z||"FILE").slice(0,4).toUpperCase(),m||"ファイル"]}
function render(){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===view));const q=e.search.value.trim();if(view==="files"){const f=items.find(x=>x.id===folder);e.pageTitle.textContent=f?.name||"マイファイル";e.sub.textContent=q?`「${q}」の検索結果`:"ファイルやフォルダを整理できます。"}else{e.pageTitle.textContent=view==="recent"?"最近":"ゴミ箱";e.sub.textContent=view==="recent"?"最近更新されたファイルです。":"完全に削除するまで保存容量を使用します。"}e.folder.classList.toggle("hidden",view!=="files");renderCrumbs();renderList();const used=items.filter(x=>x.type==="file").reduce((s,x)=>s+Number(x.size||0),0);e.storageText.textContent=`${bytes(used)} / 約700 MB`;e.storageBar.style.width=`${Math.max(used?1:0,Math.min(100,used/QUOTA*100))}%`}
function renderCrumbs(){e.crumbs.replaceChildren();if(view!=="files")return;const m=map(),chain=[];let id=folder;while(id&&id!==ROOT&&m.has(id)){chain.unshift(m.get(id));id=m.get(id).parentId}const add=(name,id)=>{const b=document.createElement("button");b.type="button";b.textContent=name;b.onclick=()=>{folder=id;render()};e.crumbs.append(b)};add("マイファイル",ROOT);chain.forEach(x=>{const s=document.createElement("span");s.textContent="›";e.crumbs.append(s);add(x.name,x.id)})}
function renderList(){const a=visible();e.list.replaceChildren();e.count.textContent=`${a.length}個のアイテム`;a.forEach(x=>e.list.append(row(x)));const z=!a.length;e.empty.classList.toggle("hidden",!z);e.list.closest(".file-table-wrap").classList.toggle("hidden",z);if(view==="trash"){e.emptyTitle.textContent="ゴミ箱は空です";e.emptyText.textContent="削除したファイルとフォルダがここに表示されます。";e.emptyUpload.classList.add("hidden")}else{e.emptyTitle.textContent=e.search.value?"見つかりませんでした":"まだファイルがありません";e.emptyText.textContent=e.search.value?"別の名前で検索してください。":"ファイルをここへドラッグするか、アップロードボタンを押してください。";e.emptyUpload.classList.toggle("hidden",!!e.search.value)}}
function row(x){const tr=document.createElement("tr"),k=kind(x),td1=document.createElement("td"),w=document.createElement("div"),ic=document.createElement("span"),nb=document.createElement("button"),st=document.createElement("strong"),sm=document.createElement("small");w.className="file-name-cell";ic.className=`file-icon ${k[0]}`;ic.textContent=k[1];nb.className="file-name-button";nb.type="button";st.textContent=x.name||"名前なし";sm.textContent=k[2];nb.append(st,sm);nb.onclick=()=>open(x);w.append(ic,nb);td1.append(w);const td2=document.createElement("td"),td3=document.createElement("td"),td4=document.createElement("td");td2.textContent=date(x.updatedAt||x.createdAt);td3.textContent=x.type==="folder"?"—":bytes(x.size);const wrap=document.createElement("div"),mb=document.createElement("button"),menu=document.createElement("div");wrap.className="row-menu-wrap";mb.className="row-menu-button";mb.type="button";mb.textContent="•••";menu.className="row-menu hidden";const acts=view==="trash"?[["復元",()=>restore(x)],["完全に削除",()=>remove(x),"danger"]]:[[x.type==="folder"?"開く":"プレビュー",()=>open(x)],...(x.type==="file"?[["ダウンロード",()=>download(x)]]:[]),["名前を変更",()=>rename(x)],["ゴミ箱へ移動",()=>trash(x),"danger"]];acts.forEach(([n,f,c])=>{const b=document.createElement("button");b.type="button";b.textContent=n;if(c)b.className=c;b.onclick=ev=>{ev.stopPropagation();menu.classList.add("hidden");f()};menu.append(b)});mb.onclick=ev=>{ev.stopPropagation();document.querySelectorAll(".row-menu").forEach(n=>n!==menu&&n.classList.add("hidden"));menu.classList.toggle("hidden")};wrap.append(mb,menu);td4.append(wrap);tr.append(td1,td2,td3,td4);return tr}
document.addEventListener("click",()=>document.querySelectorAll(".row-menu").forEach(n=>n.classList.add("hidden")));

const chunks=id=>collection(db,"users",user.uid,"items",id,"chunks");
function to64(a){let s="",step=32768;for(let i=0;i<a.length;i+=step)s+=String.fromCharCode(...a.subarray(i,Math.min(i+step,a.length)));return btoa(s)}
function from64(s){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
async function blob(x){const s=await getDocs(query(chunks(x.id),orderBy("index","asc")));if(s.empty&&x.size)throw Error("ファイルデータが見つかりません。");return new Blob(s.docs.map(d=>from64(d.data().data||"")),{type:x.mimeType||"application/octet-stream"})}
function clearPreview(){if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null}}
async function open(x){if(x.trashed)return;if(x.type==="folder"){view="files";folder=x.id;e.search.value="";render();return}clearPreview();e.previewName.textContent=x.name;e.previewMeta.textContent=`${bytes(x.size)} ・ ${date(x.updatedAt||x.createdAt)}`;e.previewBody.innerHTML='<div class="preview-unavailable"><div>◌</div><p>Firestoreから読み込んでいます…</p></div>';e.preview.showModal();try{previewUrl=URL.createObjectURL(await blob(x));const m=x.mimeType||"";e.previewBody.replaceChildren();let n;if(m.startsWith("image/")){n=document.createElement("img");n.src=previewUrl;n.alt=x.name}else if(m.startsWith("video/")){n=document.createElement("video");n.src=previewUrl;n.controls=true}else if(m.startsWith("audio/")){n=document.createElement("audio");n.src=previewUrl;n.controls=true}else if(m==="application/pdf"||x.name.toLowerCase().endsWith(".pdf")){n=document.createElement("iframe");n.src=previewUrl;n.title=x.name}else{n=document.createElement("div");n.className="preview-unavailable";n.innerHTML="<div>▤</div><h2>直接表示できません</h2><p>ダウンロードしてください。</p>";const b=document.createElement("button");b.className="primary-button";b.textContent="ダウンロード";b.onclick=()=>download(x);n.append(b)}e.previewBody.append(n)}catch(err){e.previewBody.innerHTML=`<div class="preview-unavailable"><div>!</div><h2>プレビューできませんでした</h2><p>${msg(err)}</p></div>`}}
e.closePreview.onclick=()=>{e.preview.close();clearPreview()};e.preview.addEventListener("close",clearPreview);
async function download(x){try{const u=URL.createObjectURL(await blob(x)),a=document.createElement("a");a.href=u;a.download=x.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}catch(err){toast(msg(err),"error")}}
function descendants(id){const r=[];(function walk(p){items.filter(x=>x.parentId===p).forEach(x=>{r.push(x);if(x.type==="folder")walk(x.id)})})(id);return r}
async function batches(a,fn){for(let i=0;i<a.length;i+=450){const b=writeBatch(db);a.slice(i,i+450).forEach(x=>fn(b,x,i));await b.commit()}}
async function trash(x){if(!await confirmBox("ゴミ箱へ移動しますか？",x.type==="folder"?"フォルダ内もまとめて移動します。":`「${x.name}」を移動します。`,"移動する"))return;try{await batches([x,...descendants(x.id)],(b,t)=>b.update(doc(db,"users",user.uid,"items",t.id),{trashed:true,trashedAt:serverTimestamp(),updatedAt:serverTimestamp()}));toast("ゴミ箱へ移動しました。","success")}catch(err){toast(msg(err),"error")}}
async function restore(x){try{const a=[x,...descendants(x.id)],m=map(),p=x.parentId&&m.get(x.parentId)?.trashed?ROOT:(x.parentId||ROOT);for(let i=0;i<a.length;i+=450){const b=writeBatch(db);a.slice(i,i+450).forEach((t,j)=>b.update(doc(db,"users",user.uid,"items",t.id),{trashed:false,trashedAt:null,updatedAt:serverTimestamp(),...(i+j===0?{parentId:p}:{})}));await b.commit()}toast("復元しました。","success")}catch(err){toast(msg(err),"error")}}
async function deleteChunks(id){const s=await getDocs(chunks(id));await batches(s.docs,(b,d)=>b.delete(d.ref))}
async function remove(x){if(!await confirmBox("完全に削除しますか？","この操作は取り消せません。","完全に削除"))return;const a=[x,...descendants(x.id)];try{for(const f of a.filter(y=>y.type==="file"))await deleteChunks(f.id);await batches(a,(b,t)=>b.delete(doc(db,"users",user.uid,"items",t.id)));toast("完全に削除しました。","success")}catch(err){toast(msg(err),"error")}}
async function newFolder(){const n=await promptBox("新しいフォルダ","フォルダ名","新しいフォルダ","作成");if(!n)return;try{const r=doc(collection(db,"users",user.uid,"items"));await setDoc(r,{ownerId:user.uid,type:"folder",name:n,parentId:folder,trashed:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});toast("フォルダを作成しました。","success")}catch(err){toast(msg(err),"error")}}
async function rename(x){const n=await promptBox("名前を変更","新しい名前",x.name,"変更");if(!n||n===x.name)return;try{await updateDoc(doc(db,"users",user.uid,"items",x.id),{name:n,updatedAt:serverTimestamp()});toast("名前を変更しました。","success")}catch(err){toast(msg(err),"error")}}
function promptBox(t,l,v,s){return new Promise(r=>{e.textTitle.textContent=t;e.textLabel.textContent=l;e.textInput.value=v;e.textSubmit.textContent=s;e.textError.textContent="";textResolve=r;e.textDialog.showModal();setTimeout(()=>e.textInput.select(),40)})}
e.textForm.onsubmit=ev=>{ev.preventDefault();const v=e.textInput.value.trim();if(!v||v==="."||v===".."||/[\\/]/.test(v)){e.textError.textContent="1文字以上で、/ と \\ を含まない名前にしてください。";return}e.textDialog.close();textResolve?.(v);textResolve=null};e.textDialog.addEventListener("close",()=>{if(textResolve){textResolve(null);textResolve=null}});
function confirmBox(t,x,b){return new Promise(r=>{e.confirmTitle.textContent=t;e.confirmText.textContent=x;e.confirmOk.textContent=b;e.confirm.showModal();e.confirm.addEventListener("close",()=>r(e.confirm.returnValue==="ok"),{once:true})})}

async function clean(ref){try{const s=await getDocs(collection(ref,"chunks"));await batches(s.docs,(b,d)=>b.delete(d.ref))}catch(err){console.warn(err)}}
function uploadFiles(list){[...list].forEach(uploadOne)}
async function uploadOne(file){if(file.size>MAX){toast(`${file.name} は無料版の上限10MBを超えています。`,"error");return}const dest=view==="files"?folder:ROOT,ref=doc(collection(db,"users",user.uid,"items")),ctl={cancel:false},q=uploadNode(file,ctl);e.queue.classList.remove("hidden");e.queue.append(q.root);try{const a=new Uint8Array(await file.arrayBuffer()),count=Math.max(1,Math.ceil(a.length/CHUNK));for(let i=0;i<count;i++){if(ctl.cancel){const z=Error("キャンセルしました。");z.code="cancelled";throw z}const part=a.subarray(i*CHUNK,Math.min((i+1)*CHUNK,a.length));await setDoc(doc(collection(ref,"chunks"),String(i).padStart(5,"0")),{ownerId:user.uid,index:i,data:to64(part),byteLength:part.length});const done=Math.min(file.size,(i+1)*CHUNK),p=file.size?done/file.size*100:100;q.bar.style.width=`${p}%`;q.status.textContent=`${Math.round(p)}% ・ ${bytes(done)} / ${bytes(file.size)}`}await setDoc(ref,{ownerId:user.uid,type:"file",name:file.name,parentId:dest,storageMode:"firestore-chunks",chunkCount:count,mimeType:file.type||"application/octet-stream",size:file.size,trashed:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});q.status.textContent="完了";q.bar.style.width="100%";setTimeout(()=>{q.root.remove();cleanQueue()},900)}catch(err){await clean(ref);q.root.remove();cleanQueue();if(err.code!=="cancelled")toast(`${file.name}: ${msg(err)}`,"error")}}
function uploadNode(file,ctl){const root=document.createElement("div"),icon=document.createElement("span"),info=document.createElement("div"),strong=document.createElement("strong"),status=document.createElement("small"),progress=document.createElement("div"),bar=document.createElement("i"),cancel=document.createElement("button");root.className="upload-item";icon.textContent="⇧";info.className="upload-info";strong.textContent=file.name;status.textContent=`準備中 ・ ${bytes(file.size)}`;progress.className="progress";progress.append(bar);info.append(strong,status,progress);cancel.type="button";cancel.className="upload-cancel";cancel.textContent="×";cancel.onclick=()=>{ctl.cancel=true;cancel.disabled=true;status.textContent="キャンセル中…"};root.append(icon,info,cancel);return{root,bar,status}}
const cleanQueue=()=>{if(!e.queue.children.length)e.queue.classList.add("hidden")};

[e.upload,e.uploadTop,e.emptyUpload].forEach(b=>b.onclick=()=>e.input.click());e.input.onchange=()=>{uploadFiles(e.input.files);e.input.value=""};e.folder.onclick=newFolder;
["dragenter","dragover","dragleave","drop"].forEach(n=>document.addEventListener(n,x=>{x.preventDefault();x.stopPropagation()}));document.addEventListener("dragenter",()=>{drag++;e.overlay.classList.remove("hidden")});document.addEventListener("dragleave",()=>{drag=Math.max(0,drag-1);if(!drag)e.overlay.classList.add("hidden")});document.addEventListener("drop",x=>{drag=0;e.overlay.classList.add("hidden");uploadFiles(x.dataTransfer.files)});
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>{view=b.dataset.view;folder=ROOT;e.search.value="";closeSide();render()});e.search.oninput=render;e.sort.onclick=()=>{sort=sort==="updated"?"name":"updated";e.sort.textContent=sort==="updated"?"更新順 ↕":"名前順 ↕";render()};e.refresh.onclick=()=>{render();toast("更新しました。","success")};document.addEventListener("keydown",x=>{if((x.ctrlKey||x.metaKey)&&x.key.toLowerCase()==="k"){x.preventDefault();e.search.focus()}});
e.user.onclick=x=>{x.stopPropagation();e.menu.classList.toggle("hidden")};document.addEventListener("click",()=>e.menu.classList.add("hidden"));e.menu.onclick=x=>x.stopPropagation();
const openSide=()=>{e.sidebar.classList.add("open");e.shade.classList.remove("hidden")},closeSide=()=>{e.sidebar.classList.remove("open");e.shade.classList.add("hidden")};e.mobile.onclick=openSide;e.closeSide.onclick=closeSide;e.shade.onclick=closeSide;
setMode("login");setTimeout(()=>{if(!user&&!e.load.classList.contains("hidden"))show("auth")},7000);
